"""add_stock_and_margins

Revision ID: b3d6f00c4bca
Revises: 20260520_0001
Create Date: 2026-06-03 14:12:49.395042
"""
from alembic import op
import sqlalchemy as sa


revision = 'b3d6f00c4bca'
down_revision = '20260520_0001'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
