"""add_customers_and_cash_registers

Revision ID: e1ef602ca919
Revises: e6g9h33f7efd
Create Date: 2026-06-07 20:32:26.929529
"""
from alembic import op
import sqlalchemy as sa


revision = 'e1ef602ca919'
down_revision = 'e6g9h33f7efd'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rut', sa.String(length=20), nullable=True),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_nombre'), 'customers', ['nombre'], unique=False)
    op.create_index(op.f('ix_customers_rut'), 'customers', ['rut'], unique=True)
    op.create_table('cash_registers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_apertura', sa.DateTime(), nullable=False),
    sa.Column('fecha_cierre', sa.DateTime(), nullable=True),
    sa.Column('monto_inicial', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monto_final_esperado', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('monto_final_real', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('diferencia', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_registers_id'), 'cash_registers', ['id'], unique=False)
    op.add_column('sales', sa.Column('cliente_id', sa.Integer(), nullable=True))
    op.add_column('sales', sa.Column('caja_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sales', 'cash_registers', ['caja_id'], ['id'])
    op.create_foreign_key(None, 'sales', 'customers', ['cliente_id'], ['id'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'caja_id')
    op.drop_column('sales', 'cliente_id')
    op.drop_index(op.f('ix_cash_registers_id'), table_name='cash_registers')
    op.drop_table('cash_registers')
    op.drop_index(op.f('ix_customers_rut'), table_name='customers')
    op.drop_index(op.f('ix_customers_nombre'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
